// apps/cli/src/components/screens/cookie-sync-confirm-screen.tsx
import { useEffect, useRef, useState } from "react";
import { Box, Text, useInput } from "ink";
import figures from "figures";
import type { ChangesFor, SavedFlow } from "@expect/shared/models";
import { trackEvent } from "../../utils/session-analytics";
import { useColors } from "../theme-context";
import { Logo } from "../ui/logo";
import { Spinner } from "../ui/spinner";
import { Clickable } from "../ui/clickable";
import {
  useNavigationStore,
  Screen,
  screenForTestingOrPortPicker,
} from "../../stores/use-navigation";
import { useProjectPreferencesStore } from "../../stores/use-project-preferences";
import { useInstalledBrowsers, type DetectedBrowser } from "../../hooks/use-installed-browsers";

interface CookieSyncConfirmScreenProps {
  changesFor?: ChangesFor;
  instruction?: string;
  savedFlow?: SavedFlow;
}

export const CookieSyncConfirmScreen = ({
  changesFor,
  instruction,
  savedFlow,
}: CookieSyncConfirmScreenProps) => {
  const COLORS = useColors();
  const setScreen = useNavigationStore((state) => state.setScreen);
  const setCookieBrowserKeys = useProjectPreferencesStore((state) => state.setCookieBrowserKeys);
  const { data: browsers, isLoading } = useInstalledBrowsers();

  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(new Set());
  const defaultsInitialized = useRef(false);

  const items: DetectedBrowser[] = browsers ?? [];
  const itemCount = items.length;

  useEffect(() => {
    if (defaultsInitialized.current || !browsers || browsers.length === 0) return;
    defaultsInitialized.current = true;
    const defaultBrowser = browsers.find((browser) => browser.isDefault);
    if (defaultBrowser) {
      setSelectedKeys(new Set([defaultBrowser.key]));
    }
  }, [browsers]);

  const toggleKey = (key: string) => {
    setSelectedKeys((previous) => {
      const next = new Set(previous);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  };

  const confirm = () => {
    const keys = [...selectedKeys];
    setCookieBrowserKeys(keys);
    trackEvent("cookies:browser_selection", {
      selected_count: keys.length,
      browsers: keys.join(","),
    });
    if (changesFor && instruction) {
      setScreen(
        screenForTestingOrPortPicker({
          changesFor,
          instruction,
          savedFlow,
          cookieBrowserKeys: keys,
        }),
      );
    } else {
      setScreen(Screen.Main());
    }
  };

  useInput((input, key) => {
    if (isLoading) return;

    if (key.downArrow || input === "j" || (key.ctrl && input === "n")) {
      setHighlightedIndex((previous) => Math.min(itemCount - 1, previous + 1));
    }

    if (key.upArrow || input === "k" || (key.ctrl && input === "p")) {
      setHighlightedIndex((previous) => Math.max(0, previous - 1));
    }

    if (input === " " && itemCount > 0) {
      const item = items[highlightedIndex];
      if (item) toggleKey(item.key);
    }

    if (input === "a") {
      const allKeys = items.map((browser) => browser.key);
      setSelectedKeys(new Set(allKeys));
    }

    if (input === "n") {
      setSelectedKeys(new Set());
    }

    if (key.return) {
      confirm();
    }

    if (key.escape) {
      setScreen(Screen.Main());
    }
  });

  const selectedCount = selectedKeys.size;

  return (
    <Box flexDirection="column" width="100%" paddingY={1} paddingX={1}>
      <Box>
        <Logo />
        <Text wrap="truncate">
          {" "}
          <Text color={COLORS.DIM}>{figures.pointerSmall}</Text>{" "}
          <Text color={COLORS.TEXT}>{instruction ?? "Select browsers for cookie sync"}</Text>
        </Text>
      </Box>

      <Box marginTop={1}>
        {selectedCount > 0 && (
          <Text color={COLORS.GREEN}>
            {figures.tick} Your signed-in session will be synced from {selectedCount} browser
            {selectedCount === 1 ? "" : "s"}
          </Text>
        )}
        {selectedCount === 0 && (
          <Text color={COLORS.YELLOW}>
            {figures.warning} No browsers selected — tests run without authentication
          </Text>
        )}
      </Box>

      {isLoading && (
        <Box marginTop={1}>
          <Spinner message="Detecting installed browsers" />
        </Box>
      )}

      {!isLoading && (
        <Box flexDirection="column" marginTop={1}>
          {items.map((browser, index) => {
            const isHighlighted = index === highlightedIndex;
            const isSelected = selectedKeys.has(browser.key);

            return (
              <Clickable
                key={browser.key}
                onClick={() => {
                  setHighlightedIndex(index);
                  toggleKey(browser.key);
                }}
              >
                <Box>
                  <Text color={isHighlighted ? COLORS.PRIMARY : COLORS.DIM}>
                    {isHighlighted ? `${figures.pointer} ` : "  "}
                  </Text>
                  <Text color={isSelected ? COLORS.PRIMARY : COLORS.DIM}>
                    {isSelected ? figures.checkboxOn : figures.checkboxOff}{" "}
                  </Text>
                  <Text color={isHighlighted ? COLORS.PRIMARY : COLORS.TEXT} bold={isHighlighted}>
                    {browser.displayName}
                  </Text>
                  {browser.isDefault && <Text color={COLORS.DIM}> (default)</Text>}
                </Box>
              </Clickable>
            );
          })}
        </Box>
      )}
    </Box>
  );
};

// apps/cli-solid/src/routes/cookie-sync-confirm/cookie-sync-confirm-screen.tsx
import { createSignal, createResource, createEffect, For, Show } from "solid-js";
import { Effect, Option } from "effect";
import { useKeyboard } from "@opentui/solid";
import { Browsers, layerLive, browserKeyOf, browserDisplayName } from "@neuve/cookies";
import type { BrowserKey } from "@neuve/cookies";
import type { ChangesFor, SavedFlow } from "@neuve/shared/models";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { useNavigation, Screen, screenForTestingOrPortPicker } from "../../context/navigation";
import { useProject } from "../../context/project";
import { Logo } from "../../renderables/logo";
import { COLORS } from "../../constants";

interface DetectedBrowser {
  readonly key: BrowserKey;
  readonly displayName: string;
  readonly isDefault: boolean;
}

const fetchInstalledBrowsers = (): Promise<DetectedBrowser[]> =>
  Effect.gen(function* () {
    const browsers = yield* Browsers;
    const allBrowsers = yield* browsers.list.pipe(
      Effect.catchTag("ListBrowsersError", () => Effect.succeed([])),
    );
    const maybeDefault = yield* browsers.defaultBrowser().pipe(
      Effect.map(Option.map(browserKeyOf)),
      Effect.map(Option.getOrUndefined),
      Effect.catchTag("ListBrowsersError", () => Effect.succeed(undefined)),
    );

    const seen = new Set<string>();
    const result: DetectedBrowser[] = [];
    for (const browser of allBrowsers) {
      const key = browserKeyOf(browser);
      if (seen.has(key)) continue;
      seen.add(key);
      result.push({
        key,
        displayName: browserDisplayName(browser),
        isDefault: key === maybeDefault,
      });
    }
    return result;
  }).pipe(
    Effect.provide(layerLive),
    Effect.provide(NodeServices.layer),
    Effect.tapCause((cause) => Effect.logWarning("Browser detection failed", { cause })),
    Effect.catchCause(() => Effect.succeed([] as DetectedBrowser[])),
    Effect.runPromise,
  );

interface CookieSyncConfirmScreenProps {
  readonly changesFor?: ChangesFor;
  readonly instruction?: string;
  readonly savedFlow?: SavedFlow;
}

const POINTER = "\u25B8";
const CHECKBOX_ON = "\u2611";
const CHECKBOX_OFF = "\u2610";
const TICK = "\u2714";
const WARNING = "\u26A0";
const POINTER_SMALL = "\u203A";

export const CookieSyncConfirmScreen = (props: CookieSyncConfirmScreenProps) => {
  const navigation = useNavigation();
  const project = useProject();

  const [browsers] = createResource(fetchInstalledBrowsers);
  const [highlightedIndex, setHighlightedIndex] = createSignal(0);
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(new Set());
  const [defaultsInitialized, setDefaultsInitialized] = createSignal(false);

  const items = (): DetectedBrowser[] => browsers() ?? [];
  const isLoading = () => browsers.loading;
  const selectedCount = () => selectedKeys().size;

  createEffect(() => {
    const browserList = browsers();
    if (defaultsInitialized() || !browserList || browserList.length === 0) return;
    setDefaultsInitialized(true);
    const defaultBrowser = browserList.find((browser) => browser.isDefault);
    if (defaultBrowser) {
      setSelectedKeys(new Set([defaultBrowser.key]));
    }
  });

  const toggleKey = (key: string) => {
    setSelectedKeys((previous) => {
      const next = new Set(previous);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  };

  const confirm = () => {
    const keys = [...selectedKeys()];
    project.setCookieBrowserKeys(keys);

    if (props.changesFor && props.instruction) {
      navigation.navigateTo(
        screenForTestingOrPortPicker({
          changesFor: props.changesFor,
          instruction: props.instruction,
          savedFlow: props.savedFlow,
          cookieBrowserKeys: keys,
        }),
      );
    } else {
      navigation.setScreen(Screen.Main());
    }
  };

  useKeyboard((event) => {
    if (isLoading()) return;

    const itemCount = items().length;

    if (event.name === "down" || event.name === "j") {
      setHighlightedIndex((previous) => Math.min(itemCount - 1, previous + 1));
      return;
    }

    if (event.name === "up" || event.name === "k") {
      setHighlightedIndex((previous) => Math.max(0, previous - 1));
      return;
    }

    if (event.name === " " && itemCount > 0) {
      const item = items()[highlightedIndex()];
      if (item) toggleKey(item.key);
      return;
    }

    if (event.name === "a" && !event.ctrl) {
      const allKeys: string[] = items().map((browser) => browser.key);
      setSelectedKeys(new Set(allKeys));
      return;
    }

    if (event.name === "n" && !event.ctrl) {
      setSelectedKeys(new Set<string>());
      return;
    }

    if (event.name === "return") {
      confirm();
      return;
    }
  });

  return (
    <box flexDirection="column" width="100%" paddingTop={1} paddingBottom={1} paddingLeft={1} paddingRight={1}>
      <box>
        <Logo />
        <text>
          {" "}
          <span style={{ fg: COLORS.DIM }}>{POINTER_SMALL}</span>
          {" "}
          <span style={{ fg: COLORS.TEXT }}>{props.instruction ?? "Select browsers for cookie sync"}</span>
        </text>
      </box>

      <box marginTop={1}>
        <Show when={selectedCount() > 0}>
          <text style={{ fg: COLORS.GREEN }}>
            {TICK} Your signed-in session will be synced from {selectedCount()} browser{selectedCount() === 1 ? "" : "s"}
          </text>
        </Show>
        <Show when={selectedCount() === 0}>
          <text style={{ fg: COLORS.YELLOW }}>
            {WARNING} No browsers selected — tests run without authentication
          </text>
        </Show>
      </box>

      <Show when={isLoading()}>
        <box marginTop={1}>
          <text style={{ fg: COLORS.DIM }}>Detecting installed browsers...</text>
        </box>
      </Show>

      <Show when={!isLoading()}>
        <box flexDirection="column" marginTop={1}>
          <For each={items()}>
            {(browser, index) => {
              const isHighlighted = () => index() === highlightedIndex();
              const isSelected = () => selectedKeys().has(browser.key);

              return (
                <box>
                  <text style={{ fg: isHighlighted() ? COLORS.PRIMARY : COLORS.DIM }}>
                    {isHighlighted() ? `${POINTER} ` : "  "}
                  </text>
                  <text style={{ fg: isSelected() ? COLORS.PRIMARY : COLORS.DIM }}>
                    {isSelected() ? CHECKBOX_ON : CHECKBOX_OFF}{" "}
                  </text>
                  <text>
                    <span style={{ fg: isHighlighted() ? COLORS.PRIMARY : COLORS.TEXT, bold: isHighlighted() }}>
                      {browser.displayName}
                    </span>
                  </text>
                  {browser.isDefault && <text style={{ fg: COLORS.DIM }}> (default)</text>}
                </box>
              );
            }}
          </For>
        </box>
      </Show>
    </box>
  );
};
