// apps/cli-solid/src/renderables/input.tsx
import { createSignal, createEffect, Show } from "solid-js";
import { useKeyboard } from "@opentui/solid";
import { useInputFocus } from "../context/input-focus";
import { COLORS } from "../constants";

interface InputProps {
  readonly value: string;
  readonly onChange: (value: string) => void;
  readonly onSubmit?: (value: string) => void;
  readonly placeholder?: string;
  readonly focus?: boolean;
  readonly multiline?: boolean;
  readonly onUpArrowAtTop?: () => void;
  readonly onDownArrowAtBottom?: () => void;
  readonly onAtTrigger?: () => void;
}

const isWordChar = (character: string): boolean => /\w/.test(character);

const findPreviousWordBoundary = (text: string, from: number): number => {
  let index = from - 1;
  while (index > 0 && !isWordChar(text[index]!)) index--;
  while (index > 0 && isWordChar(text[index - 1]!)) index--;
  return Math.max(0, index);
};

const findNextWordBoundary = (text: string, from: number): number => {
  let index = from;
  while (index < text.length && isWordChar(text[index]!)) index++;
  while (index < text.length && !isWordChar(text[index]!)) index++;
  return index;
};

const findCursorLineAndColumn = (
  text: string,
  offset: number,
): { lineIndex: number; column: number; lines: string[] } => {
  const lines = text.split("\n");
  let position = 0;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const lineLength = lines[lineIndex]!.length;
    if (offset <= position + lineLength) {
      return { lineIndex, column: offset - position, lines };
    }
    position += lineLength + 1;
  }
  const lastLine = lines.length - 1;
  return { lineIndex: lastLine, column: lines[lastLine]!.length, lines };
};

const resolveOffsetFromLineColumn = (
  lines: string[],
  lineIndex: number,
  column: number,
): number => {
  let offset = 0;
  for (let index = 0; index < lineIndex; index++) {
    offset += lines[index]!.length + 1;
  }
  return offset + Math.min(column, lines[lineIndex]!.length);
};

export const Input = (props: InputProps) => {
  const [cursorOffset, setCursorOffset] = createSignal(props.value.length);
  const inputFocus = useInputFocus();
  const focus = () => props.focus ?? true;

  createEffect(() => {
    inputFocus.setFocused(focus());
  });

  useKeyboard((event) => {
    if (!focus()) return;

    const value = props.value;
    let nextOffset = cursorOffset();
    let nextValue = value;
    let handled = false;

    if (event.name === "return" && !event.shift) {
      props.onSubmit?.(value);
      return;
    }

    if (event.name === "return" && event.shift && props.multiline) {
      nextValue = value.slice(0, nextOffset) + "\n" + value.slice(nextOffset);
      nextOffset++;
      handled = true;
    }

    if (!handled && event.name === "up" && props.multiline) {
      const { lineIndex, column, lines } = findCursorLineAndColumn(value, nextOffset);
      if (lineIndex > 0) {
        nextOffset = resolveOffsetFromLineColumn(lines, lineIndex - 1, column);
      } else {
        props.onUpArrowAtTop?.();
        return;
      }
      handled = true;
    }

    if (!handled && event.name === "down" && props.multiline) {
      const { lineIndex, column, lines } = findCursorLineAndColumn(value, nextOffset);
      if (lineIndex < lines.length - 1) {
        nextOffset = resolveOffsetFromLineColumn(lines, lineIndex + 1, column);
      } else {
        props.onDownArrowAtBottom?.();
        return;
      }
      handled = true;
    }

    if (!handled && event.name === "left" && !event.ctrl && !event.meta) {
      nextOffset = Math.max(0, nextOffset - 1);
      handled = true;
    }

    if (!handled && event.name === "right" && !event.ctrl && !event.meta) {
      nextOffset = Math.min(value.length, nextOffset + 1);
      handled = true;
    }

    if (!handled && event.meta && event.name === "b") {
      nextOffset = findPreviousWordBoundary(value, nextOffset);
      handled = true;
    }

    if (!handled && event.meta && event.name === "f") {
      nextOffset = findNextWordBoundary(value, nextOffset);
      handled = true;
    }

    if (!handled && event.ctrl && event.name === "a") {
      nextOffset = 0;
      handled = true;
    }

    if (!handled && event.ctrl && event.name === "e") {
      nextOffset = value.length;
      handled = true;
    }

    if (!handled && event.name === "backspace") {
      if (nextOffset > 0) {
        nextValue = value.slice(0, nextOffset - 1) + value.slice(nextOffset);
        nextOffset--;
      }
      handled = true;
    }

    if (!handled && event.name === "delete") {
      if (nextOffset < value.length) {
        nextValue = value.slice(0, nextOffset) + value.slice(nextOffset + 1);
      }
      handled = true;
    }

    if (!handled && event.ctrl && event.name === "w") {
      if (nextOffset > 0) {
        const boundary = findPreviousWordBoundary(value, nextOffset);
        nextValue = value.slice(0, boundary) + value.slice(nextOffset);
        nextOffset = boundary;
      }
      handled = true;
    }

    if (!handled && !event.ctrl && !event.meta && event.name.length === 1) {
      const character = event.name;
      if (character === "@" && value === "" && props.onAtTrigger) {
        props.onAtTrigger();
        return;
      }
      nextValue = value.slice(0, nextOffset) + character + value.slice(nextOffset);
      nextOffset += character.length;
      handled = true;
    }

    if (!handled) return;

    nextOffset = Math.max(0, Math.min(nextValue.length, nextOffset));
    setCursorOffset(nextOffset);

    if (nextValue !== value) {
      props.onChange(nextValue);
    }
  });

  const displayValue = () => {
    const value = props.value;
    if (value.length === 0 && props.placeholder) {
      return props.placeholder;
    }
    return value;
  };

  const displayColor = () => {
    if (props.value.length === 0 && props.placeholder) {
      return COLORS.DIM;
    }
    return COLORS.TEXT;
  };

  return (
    <box flexGrow={1}>
      <text style={{ fg: displayColor() }}>{displayValue()}</text>
      <Show when={focus() && props.value.length === 0 && !props.placeholder}>
        <text style={{ fg: COLORS.DIM }}>{" "}</text>
      </Show>
    </box>
  );
};

// apps/cli/src/components/ui/input.tsx
import React, { useState, useEffect } from "react";
import { Text, useInput } from "ink";
import pc from "picocolors";
import { stripMouseSequences } from "../../hooks/mouse-context.js";

interface InputProps {
  readonly value: string;
  readonly onChange: (value: string) => void;
  readonly onSubmit?: (value: string) => void;
  readonly onUpArrowAtTop?: () => void;
  readonly onDownArrowAtBottom?: () => void;
  readonly placeholder?: string;
  readonly focus?: boolean;
  readonly mask?: string;
  readonly showCursor?: boolean;
  readonly highlightPastedText?: boolean;
  readonly multiline?: boolean;
}

const isWordChar = (character: string): boolean => /\w/.test(character);

const findPreviousWordBoundary = (text: string, from: number): number => {
  let index = from - 1;
  while (index > 0 && !isWordChar(text[index]!)) index--;
  while (index > 0 && isWordChar(text[index - 1]!)) index--;
  return index;
};

const findNextWordBoundary = (text: string, from: number): number => {
  let index = from;
  while (index < text.length && isWordChar(text[index]!)) index++;
  while (index < text.length && !isWordChar(text[index]!)) index++;
  return index;
};

const findCursorLineAndColumn = (
  text: string,
  offset: number,
): { lineIndex: number; column: number; lines: string[] } => {
  const lines = text.split("\n");
  let position = 0;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const lineLength = lines[lineIndex]!.length;
    if (offset <= position + lineLength) {
      return { lineIndex, column: offset - position, lines };
    }
    position += lineLength + 1;
  }
  const lastLine = lines.length - 1;
  return { lineIndex: lastLine, column: lines[lastLine]!.length, lines };
};

const resolveOffsetFromLineColumn = (
  lines: string[],
  lineIndex: number,
  column: number,
): number => {
  let offset = 0;
  for (let index = 0; index < lineIndex; index++) {
    offset += lines[index]!.length + 1;
  }
  return offset + Math.min(column, lines[lineIndex]!.length);
};

export const Input = ({
  value: originalValue,
  placeholder = "",
  focus = true,
  mask,
  highlightPastedText = false,
  showCursor = true,
  multiline = false,
  onChange,
  onSubmit,
  onUpArrowAtTop,
  onDownArrowAtBottom,
}: InputProps) => {
  const [state, setState] = useState({
    cursorOffset: (originalValue || "").length,
    cursorWidth: 0,
  });

  const { cursorOffset, cursorWidth } = state;

  useEffect(() => {
    setState((previousState) => {
      if (!focus || !showCursor) return previousState;

      const newValue = originalValue || "";
      if (previousState.cursorOffset > newValue.length - 1) {
        return { cursorOffset: newValue.length, cursorWidth: 0 };
      }

      return previousState;
    });
  }, [originalValue, focus, showCursor]);

  const cursorActualWidth = highlightPastedText ? cursorWidth : 0;
  const value = mask ? mask.repeat(originalValue.length) : originalValue;
  let renderedValue = value;
  let renderedPlaceholder = placeholder ? pc.gray(placeholder) : undefined;

  if (showCursor && focus) {
    renderedPlaceholder =
      placeholder.length > 0
        ? pc.inverse(placeholder[0]!) + pc.gray(placeholder.slice(1))
        : pc.inverse(" ");

    renderedValue = value.length > 0 ? "" : pc.inverse(" ");

    let characterIndex = 0;
    for (const character of value) {
      const isAtCursor =
        characterIndex >= cursorOffset - cursorActualWidth && characterIndex <= cursorOffset;
      if (isAtCursor && character === "\n") {
        renderedValue += pc.inverse(" ") + "\n";
      } else {
        renderedValue += isAtCursor ? pc.inverse(character) : character;
      }
      characterIndex++;
    }

    if (value.length > 0 && cursorOffset === value.length) {
      renderedValue += pc.inverse(" ");
    }
  }

  useInput(
    (input, key) => {
      if (
        (!multiline && (key.upArrow || key.downArrow)) ||
        (key.ctrl && input === "c") ||
        key.tab ||
        (key.shift && key.tab)
      ) {
        return;
      }

      let nextCursorOffset = cursorOffset;
      let nextValue = originalValue;
      let nextCursorWidth = 0;
      let handled = false;

      if (multiline && key.upArrow && showCursor) {
        const { lineIndex, column, lines } = findCursorLineAndColumn(originalValue, cursorOffset);
        if (lineIndex > 0) {
          nextCursorOffset = resolveOffsetFromLineColumn(lines, lineIndex - 1, column);
        } else {
          onUpArrowAtTop?.();
        }
        handled = true;
      } else if (multiline && key.downArrow && showCursor) {
        const { lineIndex, column, lines } = findCursorLineAndColumn(originalValue, cursorOffset);
        if (lineIndex < lines.length - 1) {
          nextCursorOffset = resolveOffsetFromLineColumn(lines, lineIndex + 1, column);
        } else {
          onDownArrowAtBottom?.();
        }
        handled = true;
      } else if (key.ctrl && input === "u") {
        if (cursorOffset > 0) {
          nextValue = originalValue.slice(cursorOffset);
          nextCursorOffset = 0;
        }
        handled = true;
      } else if (key.ctrl && input === "w") {
        if (cursorOffset > 0) {
          const wordBoundary = findPreviousWordBoundary(originalValue, cursorOffset);
          nextValue = originalValue.slice(0, wordBoundary) + originalValue.slice(cursorOffset);
          nextCursorOffset = wordBoundary;
        }
        handled = true;
      } else if (key.meta && input === "b" && showCursor) {
        nextCursorOffset = findPreviousWordBoundary(originalValue, cursorOffset);
        handled = true;
      } else if (key.meta && input === "f" && showCursor) {
        nextCursorOffset = findNextWordBoundary(originalValue, cursorOffset);
        handled = true;
      } else if (key.meta && (key.backspace || key.delete)) {
        if (cursorOffset > 0) {
          const wordBoundary = findPreviousWordBoundary(originalValue, cursorOffset);
          nextValue = originalValue.slice(0, wordBoundary) + originalValue.slice(cursorOffset);
          nextCursorOffset = wordBoundary;
        }
        handled = true;
      } else if (key.meta) {
        return;
      }

      if (!handled) {
        if (key.return) {
          if (multiline && key.shift) {
            nextValue =
              originalValue.slice(0, cursorOffset) + "\n" + originalValue.slice(cursorOffset);
            nextCursorOffset++;
          } else {
            if (onSubmit) onSubmit(originalValue);
            return;
          }
        } else if (key.leftArrow) {
          if (showCursor) {
            nextCursorOffset--;
          }
        } else if (key.rightArrow) {
          if (showCursor) {
            nextCursorOffset++;
          }
        } else if (key.backspace || key.delete) {
          if (cursorOffset > 0) {
            nextValue =
              originalValue.slice(0, cursorOffset - 1) +
              originalValue.slice(cursorOffset, originalValue.length);
            nextCursorOffset--;
          }
        } else {
          const cleanedInput = stripMouseSequences(input);
          if (!cleanedInput) return;
          nextValue =
            originalValue.slice(0, cursorOffset) +
            cleanedInput +
            originalValue.slice(cursorOffset, originalValue.length);
          nextCursorOffset += cleanedInput.length;
          if (cleanedInput.length > 1) {
            nextCursorWidth = cleanedInput.length;
          }
        }
      }

      if (nextCursorOffset < 0) {
        nextCursorOffset = 0;
      }

      if (nextCursorOffset > nextValue.length) {
        nextCursorOffset = nextValue.length;
      }

      setState({
        cursorOffset: nextCursorOffset,
        cursorWidth: nextCursorWidth,
      });

      if (nextValue !== originalValue) {
        onChange(nextValue);
      }
    },
    { isActive: focus },
  );

  return (
    <Text>
      {placeholder ? (value.length > 0 ? renderedValue : renderedPlaceholder) : renderedValue}
    </Text>
  );
};
