// apps/cli-solid/src/routes/port-picker/port-picker-screen.tsx
import { createSignal, createResource, For, Show } from "solid-js";
import { useKeyboard } from "@opentui/solid";
import type { ChangesFor, SavedFlow } from "@neuve/shared/models";
import type { DevServerHint } from "@neuve/shared/prompts";
import { useNavigation, Screen } from "../../context/navigation";
import { useProject } from "../../context/project";
import { detectListeningPorts, type Protocol } from "../../utils/detect-listening-ports";
import { detectNearbyProjects } from "../../utils/detect-projects";
import { Input } from "../../renderables/input";
import { Logo } from "../../renderables/logo";
import { COLORS, PORT_PICKER_VISIBLE_COUNT } from "../../constants";

interface PortPickerScreenProps {
  readonly changesFor: ChangesFor;
  readonly instruction: string;
  readonly savedFlow?: SavedFlow;
  readonly cookieBrowserKeys?: readonly string[];
}

interface PortEntry {
  readonly key: string;
  readonly port: number;
  readonly processName: string;
  readonly cwd: string;
  readonly protocol: Protocol;
}

const portEntryToUrl = (entry: PortEntry): string => `${entry.protocol}://localhost:${entry.port}`;

const deduplicateByPort = (entries: PortEntry[]): PortEntry[] => {
  const seen = new Set<number>();
  return entries.filter((entry) => {
    if (seen.has(entry.port)) return false;
    seen.add(entry.port);
    return true;
  });
};

const normalizeCustomUrl = (value: string, entries: PortEntry[]): string => {
  const trimmed = value.trim();
  const portNumber = Number(trimmed);
  if (Number.isInteger(portNumber) && portNumber >= 1 && portNumber <= 65535) {
    const matchingEntry = entries.find((entry) => entry.port === portNumber);
    const protocol = matchingEntry?.protocol ?? "http";
    return `${protocol}://localhost:${portNumber}`;
  }
  if (!/^https?:\/\//i.test(trimmed)) {
    return `https://${trimmed}`;
  }
  return trimmed;
};

const POINTER = "\u25B8";
const CHECKBOX_ON = "\u2611";
const CHECKBOX_OFF = "\u2610";
const TICK = "\u2714";
const WARNING = "\u26A0";
const ARROW_RIGHT = "\u2192";
const ELLIPSIS = "\u2026";
const POINTER_SMALL = "\u203A";

export const PortPickerScreen = (props: PortPickerScreenProps) => {
  const navigation = useNavigation();
  const project = useProject();

  const [listeningPorts] = createResource(detectListeningPorts);
  const [detectedProjects] = createResource(() => detectNearbyProjects());

  const [highlightedIndex, setHighlightedIndex] = createSignal(0);
  const initialSelectedPorts = (): Set<number> => {
    const lastUrl = project.lastBaseUrl();
    if (!lastUrl) return new Set();
    const urlMatch = lastUrl.match(/:(\d+)/);
    if (urlMatch) return new Set([Number(urlMatch[1])]);
    return new Set();
  };
  const [selectedPorts, setSelectedPorts] = createSignal<Set<number>>(initialSelectedPorts());
  const [customUrls, setCustomUrls] = createSignal<Set<string>>(new Set());
  const [isEnteringCustomUrl, setIsEnteringCustomUrl] = createSignal(false);
  const [customUrlValue, setCustomUrlValue] = createSignal("");

  const runningEntries = (): PortEntry[] =>
    (listeningPorts() ?? []).map((listening) => ({
      key: `running-${listening.port}`,
      port: listening.port,
      processName: listening.processName,
      cwd: listening.cwd,
      protocol: listening.protocol,
    }));

  const detectedEntries = (): PortEntry[] => {
    const running = runningEntries();
    const runningCwds = new Set(running.map((entry) => entry.cwd));
    const runningPortSet = new Set(running.map((entry) => entry.port));
    return deduplicateByPort(
      (detectedProjects() ?? [])
        .filter(
          (detected) =>
            !runningCwds.has(detected.path) && !runningPortSet.has(detected.defaultPort),
        )
        .map((detected) => ({
          key: `detected-${detected.path}`,
          port: detected.defaultPort,
          processName: detected.framework,
          cwd: detected.path,
          protocol: "http" as Protocol,
        })),
    );
  };

  const entries = (): PortEntry[] => [...runningEntries(), ...detectedEntries()];
  const hasRunningPorts = () => runningEntries().length > 0;

  const customUrlIndex = () => entries().length;
  const skipIndex = () => entries().length + 1;
  const itemCount = () => entries().length + 2;

  const scrollOffset = () => {
    const portListVisibleCount = PORT_PICKER_VISIBLE_COUNT - 2;
    const highlighted = highlightedIndex();
    if (highlighted < portListVisibleCount) return 0;
    return Math.min(highlighted - portListVisibleCount + 1, Math.max(0, entries().length - portListVisibleCount));
  };

  const buildDevServerHints = (selectedEntries: readonly PortEntry[]): DevServerHint[] =>
    selectedEntries
      .filter((entry) => entry.key.startsWith("detected-"))
      .flatMap((entry) => {
        const detected = (detectedProjects() ?? []).find((project) => project.path === entry.cwd);
        if (!detected?.devCommand) return [];
        return [
          {
            url: portEntryToUrl(entry),
            projectPath: detected.path,
            devCommand: detected.devCommand,
          },
        ];
      });

  const navigateToTesting = (baseUrls: readonly string[], selectedEntries: readonly PortEntry[]) => {
    const allUrls = [...baseUrls, ...customUrls()];
    const lastUrl = allUrls.length > 0 ? allUrls[0] : undefined;
    project.setLastBaseUrl(lastUrl);

    const devServerHints = buildDevServerHints(selectedEntries);

    navigation.navigateTo(
      Screen.Testing({
        changesFor: props.changesFor,
        instruction: props.instruction,
        savedFlow: props.savedFlow,
        cookieBrowserKeys: props.cookieBrowserKeys,
        baseUrls: allUrls.length > 0 ? allUrls : undefined,
        devServerHints: devServerHints.length > 0 ? devServerHints : undefined,
      }),
    );
  };

  const togglePort = (port: number) => {
    setSelectedPorts((previous) => {
      const next = new Set(previous);
      if (next.has(port)) {
        next.delete(port);
      } else {
        next.add(port);
      }
      return next;
    });
  };

  const confirmSelection = () => {
    if (highlightedIndex() === skipIndex()) {
      navigateToTesting([], []);
      return;
    }

    if (selectedPorts().size > 0 || customUrls().size > 0) {
      const selected = entries()
        .filter((entry) => selectedPorts().has(entry.port))
        .sort((left, right) => left.port - right.port);
      navigateToTesting(selected.map(portEntryToUrl), selected);
      return;
    }

    if (highlightedIndex() === customUrlIndex()) {
      setIsEnteringCustomUrl(true);
      return;
    }

    const entry = entries()[highlightedIndex()];
    if (entry) {
      navigateToTesting([portEntryToUrl(entry)], [entry]);
    }
  };

  const handleCustomUrlSubmit = (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) {
      setIsEnteringCustomUrl(false);
      return;
    }
    const url = normalizeCustomUrl(trimmed, entries());
    setCustomUrls((previous) => new Set([...previous, url]));
    setCustomUrlValue("");
    setIsEnteringCustomUrl(false);
  };

  useKeyboard((event) => {
    if (isEnteringCustomUrl()) {
      if (event.name === "escape") {
        setIsEnteringCustomUrl(false);
        setCustomUrlValue("");
        event.preventDefault();
      }
      return;
    }

    if (event.name === "down" || event.name === "j") {
      setHighlightedIndex((previous) => Math.min(itemCount() - 1, previous + 1));
      return;
    }

    if (event.name === "up" || event.name === "k") {
      setHighlightedIndex((previous) => Math.max(0, previous - 1));
      return;
    }

    if (event.name === " ") {
      if (highlightedIndex() === customUrlIndex()) {
        setIsEnteringCustomUrl(true);
        return;
      }
      const entry = entries()[highlightedIndex()];
      if (entry) {
        togglePort(entry.port);
      }
      return;
    }

    if (event.name === "return") {
      confirmSelection();
      return;
    }
  });

  const portListVisibleCount = () => PORT_PICKER_VISIBLE_COUNT - 2;
  const visibleItems = () => entries().slice(scrollOffset(), scrollOffset() + portListVisibleCount());
  const customUrlVisible = () => scrollOffset() + portListVisibleCount() >= entries().length;
  const skipVisible = () => customUrlVisible();

  const highlightedEntry = () => entries()[highlightedIndex()];
  const isCustomUrlHighlighted = () => highlightedIndex() === customUrlIndex();
  const isSkipHighlighted = () => highlightedIndex() === skipIndex();

  const allSelectedUrls = () => [
    ...entries()
      .filter((entry) => selectedPorts().has(entry.port))
      .sort((left, right) => left.port - right.port)
      .map(portEntryToUrl),
    ...customUrls(),
  ];

  const isLoading = () => listeningPorts.loading || detectedProjects.loading;

  return (
    <box flexDirection="column" width="100%" paddingTop={1} paddingBottom={1} paddingLeft={1} paddingRight={1}>
      <box>
        <Logo />
        <text>
          {" "}
          <span style={{ fg: COLORS.DIM }}>{POINTER_SMALL}</span>
          {" "}
          <span style={{ fg: COLORS.TEXT }}>{props.instruction}</span>
        </text>
      </box>

      <box marginTop={1} flexDirection="column">
        <text style={{ fg: COLORS.DIM }}>Pick the dev server the agent should open in the browser.</text>
        <Show when={!hasRunningPorts() && detectedEntries().length > 0}>
          <text style={{ fg: COLORS.YELLOW }}>
            {WARNING} No running servers found. Showing detected projects:
          </text>
        </Show>
      </box>

      <Show when={isLoading()}>
        <box marginTop={1}>
          <text style={{ fg: COLORS.DIM }}>Detecting ports...</text>
        </box>
      </Show>

      <Show when={!isLoading()}>
        <box marginTop={1}>
          <Show when={allSelectedUrls().length > 0}>
            <text style={{ fg: COLORS.GREEN }}>
              {TICK} {allSelectedUrls().join(", ")}
            </text>
          </Show>
          <Show when={allSelectedUrls().length === 0 && !isSkipHighlighted() && !isCustomUrlHighlighted() && highlightedEntry()}>
            {(entry) => (
              <text style={{ fg: COLORS.DIM }}>
                {ARROW_RIGHT} {portEntryToUrl(entry())}
              </text>
            )}
          </Show>
          <Show when={allSelectedUrls().length === 0 && isSkipHighlighted()}>
            <text style={{ fg: COLORS.YELLOW }}>
              {WARNING} No base URL. The agent won{"'"}t know where your dev server is.
            </text>
          </Show>
        </box>

        <box flexDirection="column" marginTop={1}>
          <For each={visibleItems()}>
            {(entry, index) => {
              const actualIndex = () => index() + scrollOffset();
              const isHighlighted = () => actualIndex() === highlightedIndex();
              const isSelected = () => selectedPorts().has(entry.port);

              return (
                <box>
                  <text style={{ fg: isHighlighted() ? COLORS.PRIMARY : COLORS.DIM }}>
                    {isHighlighted() ? `${POINTER} ` : "  "}
                  </text>
                  <text style={{ fg: isSelected() ? COLORS.PRIMARY : COLORS.DIM }}>
                    {isSelected() ? CHECKBOX_ON : CHECKBOX_OFF}{" "}
                  </text>
                  <text>
                    <span style={{ fg: isHighlighted() ? COLORS.PRIMARY : COLORS.TEXT, bold: isHighlighted() }}>
                      :{entry.port}
                    </span>
                  </text>
                  {entry.processName && <text style={{ fg: COLORS.DIM }}> {entry.processName}</text>}
                  {entry.cwd && <text style={{ fg: COLORS.DIM }}> {entry.cwd}</text>}
                </box>
              );
            }}
          </For>

          <Show when={customUrlVisible()}>
            <box>
              <text style={{ fg: isCustomUrlHighlighted() ? COLORS.PRIMARY : COLORS.DIM }}>
                {isCustomUrlHighlighted() ? `${POINTER} ` : "  "}
              </text>
              <Show when={isEnteringCustomUrl()}>
                <box>
                  <text style={{ fg: COLORS.PRIMARY }}>URL: </text>
                  <Input
                    focus
                    value={customUrlValue()}
                    placeholder="https://localhost:4000 or staging.example.com"
                    onChange={setCustomUrlValue}
                    onSubmit={handleCustomUrlSubmit}
                  />
                </box>
              </Show>
              <Show when={!isEnteringCustomUrl()}>
                <text>
                  <span style={{ fg: isCustomUrlHighlighted() ? COLORS.PRIMARY : COLORS.TEXT, bold: isCustomUrlHighlighted() }}>
                    Enter a custom URL{ELLIPSIS}
                  </span>
                </text>
              </Show>
            </box>

            <For each={[...customUrls()]}>
              {(url) => (
                <box>
                  <text> </text>
                  <text style={{ fg: COLORS.PRIMARY }}>{CHECKBOX_ON} </text>
                  <text style={{ fg: COLORS.TEXT }}>{url}</text>
                </box>
              )}
            </For>
          </Show>

          <Show when={skipVisible()}>
            <box>
              <text style={{ fg: isSkipHighlighted() ? COLORS.PRIMARY : COLORS.DIM }}>
                {isSkipHighlighted() ? `${POINTER} ` : "  "}
              </text>
              <text>
                <span style={{ fg: isSkipHighlighted() ? COLORS.PRIMARY : COLORS.DIM, bold: isSkipHighlighted() }}>
                  Skip {ARROW_RIGHT} no base URL
                </span>
              </text>
            </box>
          </Show>

          <Show when={entries().length === 0 && !skipVisible()}>
            <text style={{ fg: COLORS.DIM }}>No matching ports</text>
          </Show>
        </box>
      </Show>
    </box>
  );
};

// apps/cli/src/components/screens/port-picker-screen.tsx
import { useState } from "react";
import { Box, Text, useInput } from "ink";
import figures from "figures";
import type { ChangesFor, SavedFlow } from "@neuve/shared/models";
import { PORT_PICKER_VISIBLE_COUNT } from "../../constants";
import { useColors } from "../theme-context";
import { useNavigationStore, Screen, type DevServerHint } from "../../stores/use-navigation";
import { useProjectPreferencesStore } from "../../stores/use-project-preferences";
import { useListeningPorts, type Protocol } from "../../hooks/use-listening-ports";
import { useDetectedProjects } from "../../hooks/use-detected-projects";
import { useScrollableList } from "../../hooks/use-scrollable-list";
import { trackEvent } from "../../utils/session-analytics";
import { SearchBar } from "../ui/search-bar";
import { Input } from "../ui/input";
import { Logo } from "../ui/logo";

interface PortPickerScreenProps {
  changesFor: ChangesFor;
  instruction: string;
  savedFlow?: SavedFlow;
  cookieBrowserKeys?: readonly string[];
}

interface PortEntry {
  readonly key: string;
  readonly port: number;
  readonly processName: string;
  readonly cwd: string;
  readonly protocol: Protocol;
}

const portEntryToUrl = (entry: PortEntry): string => `${entry.protocol}://localhost:${entry.port}`;

const matchesSearch = (entry: PortEntry, query: string): boolean => {
  const lowerQuery = query.toLowerCase();
  return (
    String(entry.port).includes(lowerQuery) ||
    entry.processName.toLowerCase().includes(lowerQuery) ||
    entry.cwd.toLowerCase().includes(lowerQuery)
  );
};

const isPortOrUrl = (value: string): number | undefined => {
  const trimmed = value.trim();

  const portNumber = Number(trimmed);
  if (Number.isInteger(portNumber) && portNumber >= 1 && portNumber <= 65535) {
    return portNumber;
  }

  const urlMatch = trimmed.match(/:(\d+)\/?$/);
  if (urlMatch) {
    const extracted = Number(urlMatch[1]);
    if (Number.isInteger(extracted) && extracted >= 1 && extracted <= 65535) {
      return extracted;
    }
  }

  return undefined;
};

const deduplicateByPort = (entries: PortEntry[]): PortEntry[] => {
  const seen = new Set<number>();
  return entries.filter((entry) => {
    if (seen.has(entry.port)) return false;
    seen.add(entry.port);
    return true;
  });
};

export const PortPickerScreen = ({
  changesFor,
  instruction,
  savedFlow,
  cookieBrowserKeys,
}: PortPickerScreenProps) => {
  const COLORS = useColors();
  const setScreen = useNavigationStore((state) => state.setScreen);
  const lastBaseUrl = useProjectPreferencesStore((state) => state.lastBaseUrl);
  const setLastBaseUrl = useProjectPreferencesStore((state) => state.setLastBaseUrl);
  const { data: listeningPorts = [] } = useListeningPorts();
  const { data: detectedProjects = [] } = useDetectedProjects();

  const [isSearching, setIsSearching] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [isEnteringCustomUrl, setIsEnteringCustomUrl] = useState(false);
  const [customUrlValue, setCustomUrlValue] = useState("");
  const [selectedPorts, setSelectedPorts] = useState<Set<number>>(() => {
    if (!lastBaseUrl) return new Set();
    const urlMatch = lastBaseUrl.match(/:(\d+)/);
    if (urlMatch) return new Set([Number(urlMatch[1])]);
    return new Set();
  });
  const [customUrls, setCustomUrls] = useState<Set<string>>(new Set());

  const runningEntries: PortEntry[] = listeningPorts.map((listening) => ({
    key: `running-${listening.port}`,
    port: listening.port,
    processName: listening.processName,
    cwd: listening.cwd,
    protocol: listening.protocol,
  }));

  const runningCwds = new Set(runningEntries.map((entry) => entry.cwd));
  const runningPorts = new Set(runningEntries.map((entry) => entry.port));
  const detectedEntries: PortEntry[] = deduplicateByPort(
    detectedProjects
      .filter((project) => !runningCwds.has(project.path) && !runningPorts.has(project.defaultPort))
      .map((project) => ({
        key: `detected-${project.path}`,
        port: project.defaultPort,
        processName: project.framework,
        cwd: project.path,
        protocol: "http" satisfies Protocol,
      })),
  );

  const entries: PortEntry[] = [...runningEntries, ...detectedEntries];
  const hasRunningPorts = runningEntries.length > 0;

  const filteredEntries = searchQuery
    ? entries.filter((entry) => matchesSearch(entry, searchQuery))
    : entries;

  const customUrlIndex = filteredEntries.length;
  const skipIndex = filteredEntries.length + 1;
  const itemCount = filteredEntries.length + 2;

  const { highlightedIndex, setHighlightedIndex, scrollOffset, handleNavigation } =
    useScrollableList({
      itemCount,
      visibleCount: PORT_PICKER_VISIBLE_COUNT,
    });

  const buildDevServerHints = (selectedEntries: readonly PortEntry[]): DevServerHint[] =>
    selectedEntries
      .filter((entry) => entry.key.startsWith("detected-"))
      .flatMap((entry) => {
        const project = detectedProjects.find((detected) => detected.path === entry.cwd);
        if (!project?.devCommand) return [];
        return [
          {
            url: portEntryToUrl(entry),
            projectPath: project.path,
            devCommand: project.devCommand,
          },
        ];
      });

  const navigateToTesting = (
    baseUrls: readonly string[],
    selectedEntries: readonly PortEntry[],
  ) => {
    const allUrls = [...baseUrls, ...customUrls];
    const lastUrl = allUrls.length > 0 ? allUrls[0] : undefined;
    setLastBaseUrl(lastUrl);

    if (allUrls.length === 0) {
      trackEvent("port:skipped");
    } else {
      trackEvent("port:selected", {
        port_count: allUrls.length,
        has_custom_url: customUrls.size > 0,
        source: hasRunningPorts ? "running" : "detected",
      });
    }

    const devServerHints = buildDevServerHints(selectedEntries);

    setScreen(
      Screen.Testing({
        changesFor,
        instruction,
        savedFlow,
        cookieBrowserKeys,
        baseUrls: allUrls.length > 0 ? allUrls : undefined,
        devServerHints: devServerHints.length > 0 ? devServerHints : undefined,
      }),
    );
  };

  const togglePort = (port: number) => {
    setSelectedPorts((previous) => {
      const next = new Set(previous);
      if (next.has(port)) {
        next.delete(port);
      } else {
        next.add(port);
      }
      return next;
    });
  };

  const confirmSelection = () => {
    if (highlightedIndex === skipIndex) {
      navigateToTesting([], []);
      return;
    }

    if (selectedPorts.size > 0 || customUrls.size > 0) {
      const selected = entries
        .filter((entry) => selectedPorts.has(entry.port))
        .sort((left, right) => left.port - right.port);
      navigateToTesting(selected.map(portEntryToUrl), selected);
      return;
    }

    if (highlightedIndex === customUrlIndex) {
      setIsEnteringCustomUrl(true);
      return;
    }

    const entry = filteredEntries[highlightedIndex];
    if (entry) {
      navigateToTesting([portEntryToUrl(entry)], [entry]);
    }
  };

  const normalizeCustomUrl = (value: string): string => {
    const trimmed = value.trim();
    const portNumber = Number(trimmed);
    if (Number.isInteger(portNumber) && portNumber >= 1 && portNumber <= 65535) {
      const matchingEntry = entries.find((entry) => entry.port === portNumber);
      const protocol = matchingEntry?.protocol ?? "http";
      return `${protocol}://localhost:${portNumber}`;
    }
    if (!/^https?:\/\//i.test(trimmed)) {
      return `https://${trimmed}`;
    }
    return trimmed;
  };

  const handleCustomUrlSubmit = (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) {
      setIsEnteringCustomUrl(false);
      return;
    }
    const url = normalizeCustomUrl(trimmed);
    setCustomUrls((previous) => new Set([...previous, url]));
    setCustomUrlValue("");
    setIsEnteringCustomUrl(false);
  };

  const handleSearchChange = (value: string) => {
    setSearchQuery(value);
    setHighlightedIndex(0);
  };

  const handleSearchSubmit = (value: string) => {
    const customPort = isPortOrUrl(value);
    if (customPort) {
      togglePort(customPort);
      setIsSearching(false);
      setSearchQuery("");
      return;
    }
    setIsSearching(false);
  };

  useInput((input, key) => {
    if (isEnteringCustomUrl) {
      if (key.escape) {
        setIsEnteringCustomUrl(false);
        setCustomUrlValue("");
        return;
      }
      return;
    }

    if (isSearching) {
      if (key.escape) {
        setIsSearching(false);
        return;
      }
      return;
    }

    if (handleNavigation(input, key)) return;

    if (input === "/") {
      setIsSearching(true);
      return;
    }

    if (input === " ") {
      if (highlightedIndex === customUrlIndex) {
        setIsEnteringCustomUrl(true);
        return;
      }
      const entry = filteredEntries[highlightedIndex];
      if (entry) {
        togglePort(entry.port);
      }
      return;
    }

    if (key.return) {
      confirmSelection();
    }
  });

  const portListVisibleCount = PORT_PICKER_VISIBLE_COUNT - 2;
  const visibleItems = filteredEntries.slice(scrollOffset, scrollOffset + portListVisibleCount);
  const customUrlVisible = scrollOffset + portListVisibleCount >= filteredEntries.length;
  const skipVisible = customUrlVisible;

  const highlightedEntry = filteredEntries[highlightedIndex];
  const isCustomUrlHighlighted = highlightedIndex === customUrlIndex;
  const isSkipHighlighted = highlightedIndex === skipIndex;

  const allSelectedUrls = [
    ...entries
      .filter((entry) => selectedPorts.has(entry.port))
      .sort((left, right) => left.port - right.port)
      .map(portEntryToUrl),
    ...customUrls,
  ];

  return (
    <Box flexDirection="column" width="100%" paddingY={1} paddingX={1}>
      <Box>
        <Logo />
        <Text wrap="truncate">
          {" "}
          <Text color={COLORS.DIM}>{figures.pointerSmall}</Text>{" "}
          <Text color={COLORS.TEXT}>{instruction}</Text>
        </Text>
      </Box>

      <Box marginTop={1} flexDirection="column">
        <Text color={COLORS.DIM}>Pick the dev server the agent should open in the browser.</Text>
        {!hasRunningPorts && detectedEntries.length > 0 && (
          <Text color={COLORS.YELLOW}>
            {figures.warning} No running servers found. Showing detected projects:
          </Text>
        )}
      </Box>

      <Box marginTop={1}>
        {allSelectedUrls.length > 0 && (
          <Text color={COLORS.GREEN}>
            {figures.tick} {allSelectedUrls.join(", ")}
          </Text>
        )}
        {allSelectedUrls.length === 0 &&
          !isSkipHighlighted &&
          !isCustomUrlHighlighted &&
          highlightedEntry && (
            <Text color={COLORS.DIM}>
              {figures.arrowRight} {portEntryToUrl(highlightedEntry)}
            </Text>
          )}
        {allSelectedUrls.length === 0 && isSkipHighlighted && (
          <Text color={COLORS.YELLOW}>
            {figures.warning} No base URL. The agent won{"'"}t know where your dev server is.
          </Text>
        )}
      </Box>

      <Box flexDirection="column" marginTop={1}>
        {visibleItems.map((entry, index) => {
          const actualIndex = index + scrollOffset;
          const isHighlighted = actualIndex === highlightedIndex;
          const isSelected = selectedPorts.has(entry.port);

          return (
            <Box key={entry.key}>
              <Text color={isHighlighted ? COLORS.PRIMARY : COLORS.DIM}>
                {isHighlighted ? `${figures.pointer} ` : "  "}
              </Text>
              <Text color={isSelected ? COLORS.PRIMARY : COLORS.DIM}>
                {isSelected ? figures.checkboxOn : figures.checkboxOff}{" "}
              </Text>
              <Text color={isHighlighted ? COLORS.PRIMARY : COLORS.TEXT} bold={isHighlighted}>
                :{entry.port}
              </Text>
              {entry.processName && <Text color={COLORS.DIM}> {entry.processName}</Text>}
              {entry.cwd && <Text color={COLORS.DIM}> {entry.cwd}</Text>}
            </Box>
          );
        })}
        {customUrlVisible && (
          <Box>
            <Text color={isCustomUrlHighlighted ? COLORS.PRIMARY : COLORS.DIM}>
              {isCustomUrlHighlighted ? `${figures.pointer} ` : "  "}
            </Text>
            {isEnteringCustomUrl && (
              <Box>
                <Text color={COLORS.PRIMARY}>URL: </Text>
                <Input
                  focus
                  value={customUrlValue}
                  placeholder="https://localhost:4000 or staging.example.com"
                  onChange={setCustomUrlValue}
                  onSubmit={handleCustomUrlSubmit}
                />
              </Box>
            )}
            {!isEnteringCustomUrl && (
              <Text
                color={isCustomUrlHighlighted ? COLORS.PRIMARY : COLORS.TEXT}
                bold={isCustomUrlHighlighted}
              >
                Enter a custom URL{figures.ellipsis}
              </Text>
            )}
          </Box>
        )}
        {customUrlVisible &&
          [...customUrls].map((url) => (
            <Box key={url}>
              <Text> </Text>
              <Text color={COLORS.PRIMARY}>{figures.checkboxOn} </Text>
              <Text color={COLORS.TEXT}>{url}</Text>
            </Box>
          ))}
        {skipVisible && (
          <Box>
            <Text color={isSkipHighlighted ? COLORS.PRIMARY : COLORS.DIM}>
              {isSkipHighlighted ? `${figures.pointer} ` : "  "}
            </Text>
            <Text color={isSkipHighlighted ? COLORS.PRIMARY : COLORS.DIM} bold={isSkipHighlighted}>
              Skip {figures.arrowRight} no base URL
            </Text>
          </Box>
        )}
        {filteredEntries.length === 0 && !skipVisible && (
          <Text color={COLORS.DIM}>No matching ports</Text>
        )}
      </Box>

      <SearchBar
        isSearching={isSearching}
        query={searchQuery}
        onChange={handleSearchChange}
        onSubmit={handleSearchSubmit}
      />
    </Box>
  );
};
