// apps/cli/src/components/ui/screen-heading.tsx
import { Text } from "ink";
import { theme } from "../theme-context";
import { useStdoutDimensions } from "../../hooks/use-stdout-dimensions";
import stringWidth from "string-width";

interface ScreenHeadingProps {
  title: string;
  subtitle?: string;
  showDivider?: boolean;
}

export const ScreenHeading = ({ title, subtitle, showDivider = true }: ScreenHeadingProps) => {
  const [columns] = useStdoutDimensions();
  const upperTitle = title.toUpperCase();
  const subtitleContent = subtitle ? ` │ ${subtitle}` : "";
  const textWidth = stringWidth(upperTitle) + stringWidth(subtitleContent);
  const lineWidth = showDivider ? Math.max(0, columns - textWidth - 3) : 0;

  return (
    <Text>
      <Text bold color={theme.text}>
        {upperTitle}
      </Text>
      {subtitle && <Text color={theme.textMuted}>{subtitleContent}</Text>}
      {showDivider && <Text color={theme.border}> {"─".repeat(lineWidth)}</Text>}
    </Text>
  );
};

// apps/cli-solid/src/renderables/screen-heading.tsx
import { Show } from "solid-js";
import { useTerminalDimensions } from "@opentui/solid";
import { COLORS } from "../constants";

interface ScreenHeadingProps {
  readonly title: string;
  readonly subtitle?: string;
  readonly showDivider?: boolean;
}

export const ScreenHeading = (props: ScreenHeadingProps) => {
  const dimensions = useTerminalDimensions();
  const showDivider = () => props.showDivider ?? true;
  const upperTitle = () => props.title.toUpperCase();
  const subtitleContent = () => (props.subtitle ? ` \u2502 ${props.subtitle}` : "");
  const textWidth = () => upperTitle().length + subtitleContent().length;
  const lineWidth = () => {
    if (!showDivider()) return 0;
    return Math.max(0, dimensions().width - textWidth() - 3);
  };

  return (
    <text>
      <span style={{ fg: COLORS.TEXT, bold: true }}>{upperTitle()}</span>
      <Show when={props.subtitle}>
        <span style={{ fg: COLORS.DIM }}>{subtitleContent()}</span>
      </Show>
      <Show when={showDivider()}>
        <span style={{ fg: COLORS.BORDER }}>{" "}{"\u2500".repeat(lineWidth())}</span>
      </Show>
    </text>
  );
};
