// apps/cli/src/components/screens/testing-screen.tsx
import { useEffect, useMemo, useState } from "react";
import { Box, Static, Text, useInput } from "ink";
import figures from "figures";
import { DateTime, Option } from "effect";
import * as AsyncResult from "effect/unstable/reactivity/AsyncResult";
import * as Atom from "effect/unstable/reactivity/Atom";
import { useAtom, useAtomValue } from "@effect/atom-react";
import stringWidth from "string-width";

import {
  type ChangesFor,
  type SavedFlow,
  TestPlanStep,
  type ExecutedTestPlan,
} from "@expect/shared/models";
import { TESTING_TIMER_UPDATE_INTERVAL_MS, TESTING_TOOL_TEXT_CHAR_LIMIT } from "../../constants";
import { useColors } from "../theme-context";
import { RuledBox } from "../ui/ruled-box";
import { Spinner } from "../ui/spinner";
import { TextShimmer } from "../ui/text-shimmer";
import { usePlanExecutionStore } from "../../stores/use-plan-execution-store";
import { usePreferencesStore } from "../../stores/use-preferences";
import { useNavigationStore, Screen } from "../../stores/use-navigation";
import { ScreenHeading } from "../ui/screen-heading";
import cliTruncate from "cli-truncate";
import { formatElapsedTime } from "../../utils/format-elapsed-time";
import { Image } from "../ui/image";
import { ErrorMessage } from "../ui/error-message";
import { executeFn, screenshotPathsAtom } from "../../data/execution-atom";
import { useStdoutDimensions } from "../../hooks/use-stdout-dimensions";

interface TestingScreenProps {
  changesFor: ChangesFor;
  instruction: string;
  savedFlow?: SavedFlow;
}

const getStepElapsedMs = (step: TestPlanStep): number | undefined => {
  if (Option.isNone(step.startedAt)) return undefined;
  const endMs = Option.isSome(step.endedAt)
    ? DateTime.toEpochMillis(step.endedAt.value)
    : Date.now();
  return endMs - DateTime.toEpochMillis(step.startedAt.value);
};

export const TestingScreen = ({ changesFor, instruction, savedFlow }: TestingScreenProps) => {
  const setScreen = useNavigationStore((state) => state.setScreen);
  const COLORS = useColors();
  const [columns] = useStdoutDimensions();

  const agentBackend = usePreferencesStore((state) => state.agentBackend);
  const [executionResult, triggerExecute] = useAtom(executeFn, {
    mode: "promiseExit",
  });
  const screenshotPaths = useAtomValue(screenshotPathsAtom);

  const isExecuting = AsyncResult.isWaiting(executionResult);
  const isExecutionComplete = AsyncResult.isSuccess(executionResult);
  const report = isExecutionComplete ? executionResult.value.report : undefined;

  const [executedPlan, setExecutedPlan] = useState<ExecutedTestPlan | undefined>(undefined);
  const [runStartedAt, setRunStartedAt] = useState<number | undefined>(undefined);
  const [elapsedTimeMs, setElapsedTimeMs] = useState(0);
  const [showCancelConfirmation, setShowCancelConfirmation] = useState(false);

  const elapsedTimeLabel = useMemo(() => formatElapsedTime(elapsedTimeMs), [elapsedTimeMs]);

  useEffect(() => {
    setRunStartedAt(Date.now());

    triggerExecute({
      options: {
        changesFor,
        instruction,
        isHeadless: true,
        requiresCookies: false,
        savedFlow,
      },
      agentBackend,
      onUpdate: setExecutedPlan,
    });

    return () => {
      triggerExecute(Atom.Interrupt);
    };
  }, [triggerExecute, agentBackend, changesFor, instruction, savedFlow]);

  useEffect(() => {
    if (isExecutionComplete && executedPlan && report) {
      usePlanExecutionStore.getState().setExecutedPlan(executedPlan);
      setScreen(Screen.Results({ report }));
    }
  }, [isExecutionComplete, executedPlan, report, setScreen]);

  const goToMain = () => {
    usePlanExecutionStore.getState().setExecutedPlan(undefined);
    setScreen(Screen.Main());
  };

  useEffect(() => {
    if (runStartedAt === undefined) return;
    if (!isExecuting) return;
    const interval = setInterval(() => {
      setElapsedTimeMs(Date.now() - runStartedAt);
    }, TESTING_TIMER_UPDATE_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [runStartedAt, isExecuting]);

  useInput((input, key) => {
    const normalizedInput = input.toLowerCase();

    if (showCancelConfirmation) {
      if (key.return || normalizedInput === "y") {
        setShowCancelConfirmation(false);
        goToMain();
        return;
      }
      if (key.escape || normalizedInput === "n") {
        setShowCancelConfirmation(false);
      }
      return;
    }

    if (key.escape) {
      if (AsyncResult.isFailure(executionResult)) {
        goToMain();
        return;
      }
      if (isExecuting) {
        setShowCancelConfirmation(true);
        return;
      }
      if (executedPlan && report) {
        usePlanExecutionStore.getState().setExecutedPlan(executedPlan);
        setScreen(Screen.Results({ report }));
        return;
      }
      goToMain();
    }
  });

  const completedCount = executedPlan?.steps
    ? executedPlan.steps.filter(
        (step: TestPlanStep) => step.status === "passed" || step.status === "failed",
      ).length
    : 0;
  const totalCount = executedPlan?.steps ? executedPlan.steps.length : 0;
  const currentActiveStep = executedPlan?.steps?.find(
    (step: TestPlanStep) => step.status === "active",
  );
  const runStatusLabel = currentActiveStep
    ? `Running ${currentActiveStep.title}`
    : completedCount === totalCount && totalCount > 0
      ? "Finishing up"
      : "Starting";

  const progressStateLabel = isExecuting ? "RUNNING" : "COMPLETE";
  const progressStateText = `${figures.bullet} ${progressStateLabel}`;
  const progressCountText = ` ${completedCount}/${totalCount} `;
  const elapsedTimeText = isExecuting ? ` ${figures.pointerSmall} ${elapsedTimeLabel}` : "";
  const progressRowWidth = Math.max(0, columns - 2);
  const progressBarWidth = Math.max(
    0,
    progressRowWidth -
      stringWidth(progressStateText) -
      1 -
      stringWidth(progressCountText) -
      1 -
      stringWidth(elapsedTimeText),
  );
  const filledWidth =
    totalCount > 0 ? Math.round((completedCount / totalCount) * progressBarWidth) : 0;
  const emptyWidth = progressBarWidth - filledWidth;

  return (
    <>
      <Static items={[...screenshotPaths]}>
        {(screenshotPath) => (
          <Box key={screenshotPath} paddingX={1}>
            <Image src={screenshotPath} alt={screenshotPath} />
          </Box>
        )}
      </Static>
      <Box flexDirection="column" width="100%" paddingY={1}>
        <Box paddingX={1}>
          <ScreenHeading title="Running browser test" subtitle={instruction} showDivider={false} />
        </Box>

        <Box marginTop={1} paddingX={1} alignItems="center">
          <Text bold color={COLORS.SELECTION}>
            {progressStateText}
          </Text>
          <Text> </Text>
          <Text backgroundColor={COLORS.SELECTION}>{" ".repeat(filledWidth)}</Text>
          <Text backgroundColor={COLORS.DIVIDER}>{" ".repeat(emptyWidth)}</Text>
          <Text> </Text>
          <Text backgroundColor={COLORS.DIVIDER} color={COLORS.TEXT}>
            {progressCountText}
          </Text>
          {elapsedTimeText ? <Text color={COLORS.DIM}>{elapsedTimeText}</Text> : null}
        </Box>

        <Box flexDirection="column" marginTop={1} paddingX={1}>
          {(executedPlan?.steps ?? []).map((step: TestPlanStep, stepIndex: number) => {
            const stepPrefix = `Step ${stepIndex + 1}`;
            const label = Option.isSome(step.summary) ? step.summary.value : step.title;
            const stepElapsedMs = getStepElapsedMs(step);
            const stepElapsedLabel =
              stepElapsedMs !== undefined ? formatElapsedTime(stepElapsedMs) : undefined;
            return (
              <Box key={step.id} flexDirection="column">
                {step.status === "passed" && (
                  <Text color={COLORS.GREEN}>
                    {`  ${figures.tick} ${stepPrefix} ${cliTruncate(
                      label,
                      TESTING_TOOL_TEXT_CHAR_LIMIT,
                    )}${stepElapsedLabel ? ` ${stepElapsedLabel}` : ""}`}
                  </Text>
                )}
                {step.status === "failed" && (
                  <Text color={COLORS.RED}>
                    {`  ${figures.cross} ${stepPrefix} ${cliTruncate(
                      label,
                      TESTING_TOOL_TEXT_CHAR_LIMIT,
                    )}${stepElapsedLabel ? ` ${stepElapsedLabel}` : ""}`}
                  </Text>
                )}
                {step.status === "active" && (
                  <Box>
                    <Text>{"  "}</Text>
                    <Spinner />
                    <Text> </Text>
                    <TextShimmer
                      text={`${stepPrefix} ${step.title} ${formatElapsedTime(
                        Math.round(elapsedTimeMs),
                      )}`}
                      baseColor={COLORS.SELECTION}
                      highlightColor={COLORS.PRIMARY}
                    />
                  </Box>
                )}
                {step.status !== "passed" &&
                  step.status !== "failed" &&
                  step.status !== "active" && (
                    <Text color={COLORS.DIM}>{`  ○ ${stepPrefix} ${step.title}`}</Text>
                  )}
              </Box>
            );
          })}
        </Box>

        {showCancelConfirmation && (
          <RuledBox color={COLORS.YELLOW} marginTop={1}>
            <Text color={COLORS.YELLOW} bold>
              Stop this browser run?
            </Text>
            <Text color={COLORS.DIM}>This will terminate the agent and close the browser.</Text>
            <Text color={COLORS.DIM}>
              Press <Text color={COLORS.PRIMARY}>Enter</Text> or{" "}
              <Text color={COLORS.PRIMARY}>y</Text> to stop, or{" "}
              <Text color={COLORS.PRIMARY}>Esc</Text> or <Text color={COLORS.PRIMARY}>n</Text> to
              keep it running.
            </Text>
          </RuledBox>
        )}

        {isExecuting && !showCancelConfirmation && (
          <Box marginTop={1} paddingX={1} flexDirection="column">
            <TextShimmer
              text={`${runStatusLabel}${figures.ellipsis} ${elapsedTimeLabel}`}
              baseColor={COLORS.DIM}
              highlightColor={COLORS.PRIMARY}
            />
          </Box>
        )}

        {AsyncResult.builder(executionResult)
          .onSuccess(() => (
            <Box marginTop={1} flexDirection="column" paddingX={1}>
              <Text color={COLORS.GREEN} bold>
                Done
              </Text>
            </Box>
          ))
          .orNull()}

        {AsyncResult.builder(executionResult)
          .onError((error) => (
            <Box paddingX={1}>
              <ErrorMessage message={error instanceof Error ? error.message : String(error)} />
            </Box>
          ))
          .orNull()}
      </Box>
    </>
  );
};

// apps/cli-solid/src/routes/testing/testing-screen.tsx
import { createSignal, createEffect, onCleanup, For, Show } from "solid-js";
import { useKeyboard } from "@opentui/solid";
import { Exit, Option } from "effect";
import * as Atom from "effect/unstable/reactivity/Atom";
import type {
  ChangesFor,
  SavedFlow,
  ExecutedPerfPlan,
  AnalysisStep,
} from "@neuve/shared/models";
import type { DevServerHint } from "@neuve/shared/prompts";
import { executeFn } from "@neuve/perf-agent-cli/data/execution-atom";
import type { ExecutionResult } from "@neuve/perf-agent-cli/data/execution-atom";
import { agentConfigOptionsAtom } from "@neuve/perf-agent-cli/data/config-options";
import { useNavigation, Screen } from "../../context/navigation";
import { useAgent } from "../../context/agent";
import { atomFnToPromise, atomSet, atomGet } from "../../adapters/effect-atom";
import { Logo } from "../../renderables/logo";
import { Spinner } from "../../renderables/spinner";
import { formatElapsedTime } from "../../utils/format-elapsed-time";
import { COLORS, TESTING_TIMER_UPDATE_INTERVAL_MS } from "../../constants";
import {
  type ToolCallDisplay,
  formatTokenCount,
  formatStreamingBytes,
  formatCommandPreview,
  formatArgsPreview,
  formatResultPreview,
  truncateLabel,
  getActiveStepToolCalls,
  getPlanningToolCalls,
  getStepElapsedMs,
} from "./testing-helpers";

const TICK = "\u2714";
const CROSS = "\u2718";
const CIRCLE = "\u25CB";
const ARROW_RIGHT = "\u2192";
const POINTER = "\u25B8";
const PIPE = "\u2502";
const ARROW_DOWN = "\u2193";
const ELLIPSIS = "\u2026";

interface TestingScreenProps {
  readonly changesFor: ChangesFor;
  readonly instruction: string;
  readonly savedFlow?: SavedFlow;
  readonly cookieBrowserKeys?: readonly string[];
  readonly baseUrls?: readonly string[];
  readonly devServerHints?: readonly DevServerHint[];
}

export const TestingScreen = (props: TestingScreenProps) => {
  const navigation = useNavigation();
  const agent = useAgent();

  const [executedPlan, setExecutedPlan] = createSignal<ExecutedPerfPlan | undefined>(undefined);
  const [runStartedAt, setRunStartedAt] = createSignal<number | undefined>(undefined);
  const [elapsedTimeMs, setElapsedTimeMs] = createSignal(0);
  const [showCancelConfirmation, setShowCancelConfirmation] = createSignal(false);
  const [isExecuting, setIsExecuting] = createSignal(true);
  const [executionError, setExecutionError] = createSignal<string | undefined>(undefined);

  const elapsedTimeLabel = () => formatElapsedTime(elapsedTimeMs());
  const totalCount = () => executedPlan()?.steps?.length ?? 0;

  createEffect(() => {
    const startTime = Date.now();
    setRunStartedAt(startTime);

    const agentBackend = agent.agentBackend();
    const modelPrefs = agent.modelPreferences();
    const modelPref = modelPrefs[agentBackend];

    const baseUrl =
      props.baseUrls && props.baseUrls.length > 0 ? props.baseUrls.join(", ") : undefined;

    const trigger = atomFnToPromise(executeFn);
    const promise = trigger({
      options: {
        changesFor: props.changesFor,
        instruction: props.instruction,
        isHeadless: true,
        cdpUrl: undefined,
        profileName: undefined,
        cookieBrowserKeys: props.cookieBrowserKeys ? [...props.cookieBrowserKeys] : [],
        savedFlow: props.savedFlow,
        baseUrl,
        devServerHints: props.devServerHints ? [...props.devServerHints] : undefined,
        modelPreference:
          modelPref ? { configId: modelPref.configId, value: modelPref.value } : undefined,
      },
      agentBackend,
      onUpdate: setExecutedPlan,
      onConfigOptions: (configOptions) => {
        const previous = atomGet(agentConfigOptionsAtom);
        atomSet(agentConfigOptionsAtom, {
          ...previous,
          [agentBackend]: [...configOptions],
        });
      },
    });

    promise.then((exit) => {
      setIsExecuting(false);
      if (Exit.isSuccess(exit)) {
        const result = exit.value as ExecutionResult;
        navigation.setScreen(Screen.Results({ report: result.report, videoUrl: result.videoUrl }));
      } else {
        const prettyError = String(exit.cause);
        setExecutionError(prettyError);
      }
    });

    onCleanup(() => {
      atomSet(executeFn, Atom.Interrupt);
    });
  });

  createEffect(() => {
    const started = runStartedAt();
    if (started === undefined) return;
    if (!isExecuting()) return;

    const interval = setInterval(() => {
      setElapsedTimeMs(Date.now() - started);
    }, TESTING_TIMER_UPDATE_INTERVAL_MS);

    onCleanup(() => clearInterval(interval));
  });

  const goToMain = () => {
    navigation.setScreen(Screen.Main());
  };

  useKeyboard((event) => {
    if (showCancelConfirmation()) {
      if (event.name === "return" || event.name === "y") {
        setShowCancelConfirmation(false);
        goToMain();
        return;
      }
      if (event.name === "escape" || event.name === "n") {
        setShowCancelConfirmation(false);
        return;
      }
      return;
    }

    if (event.name === "escape") {
      if (executionError()) {
        goToMain();
        return;
      }
      if (isExecuting()) {
        setShowCancelConfirmation(true);
        return;
      }
      goToMain();
    }
  });

  const planningToolCalls = () => {
    const plan = executedPlan();
    if (!plan) return [];
    return getPlanningToolCalls(plan.events);
  };

  const activeStepToolCalls = () => {
    const plan = executedPlan();
    if (!plan) return [];
    return getActiveStepToolCalls(plan.events);
  };

  return (
    <box flexDirection="column" width="100%" paddingTop={1} paddingBottom={1} paddingLeft={1} paddingRight={1}>
      <box>
        <Logo />
        <text>
          <span style={{ fg: COLORS.DIM }}>{` ${POINTER} `}</span>
          <span style={{ fg: COLORS.TEXT }}>{props.instruction}</span>
        </text>
      </box>

      {/* Planning phase — no steps yet */}
      <Show when={totalCount() === 0 && isExecuting()}>
        <box flexDirection="column" marginTop={1}>
          <box>
            <Spinner />
            <text style={{ fg: COLORS.SHIMMER_HIGHLIGHT }}>
              {` Starting${ELLIPSIS} ${elapsedTimeLabel()}`}
            </text>
          </box>
          <For each={planningToolCalls()}>
            {(display) => <ToolCallRow display={display} indent="  " />}
          </For>
        </box>
      </Show>

      {/* Step list */}
      <Show when={totalCount() > 0}>
        <box flexDirection="column" marginTop={1}>
          <For each={executedPlan()?.steps ?? []}>
            {(step, stepIndex) => (
              <StepRow
                step={step}
                stepIndex={stepIndex()}
                elapsedTimeLabel={elapsedTimeLabel()}
                toolCalls={step.status === "active" ? activeStepToolCalls() : []}
              />
            )}
          </For>
        </box>
      </Show>

      {/* Cancel confirmation */}
      <Show when={showCancelConfirmation()}>
        <box marginTop={1}>
          <text style={{ fg: COLORS.YELLOW }}>
            {"Stop run? "}
            <span style={{ fg: COLORS.PRIMARY }}>enter</span>
            {" to stop, "}
            <span style={{ fg: COLORS.PRIMARY }}>esc</span>
            {" to dismiss"}
          </text>
        </box>
      </Show>

      {/* Error display */}
      <Show when={executionError()}>
        <box flexDirection="column" marginTop={1}>
          <text style={{ fg: COLORS.RED }}>
            {`${CROSS} Execution failed`}
          </text>
          <text style={{ fg: COLORS.DIM }}>
            {executionError()}
          </text>
          <text style={{ fg: COLORS.DIM }}>
            {"Press esc to go back"}
          </text>
        </box>
      </Show>
    </box>
  );
};

interface StepRowProps {
  readonly step: AnalysisStep;
  readonly stepIndex: number;
  readonly elapsedTimeLabel: string;
  readonly toolCalls: readonly ToolCallDisplay[];
}

const StepRow = (props: StepRowProps) => {
  const num = () => `${props.stepIndex + 1}.`;
  const label = () => {
    const summary = props.step.summary;
    return Option.isSome(summary) ? summary.value : props.step.title;
  };
  const stepElapsedMs = () => getStepElapsedMs(props.step);
  const stepElapsedLabel = () => {
    const ms = stepElapsedMs();
    return ms !== undefined ? formatElapsedTime(ms) : undefined;
  };

  return (
    <box flexDirection="column">
      <Show when={props.step.status === "active"}>
        <box>
          <text style={{ fg: COLORS.DIM }}>{`  ${num()} `}</text>
          <Spinner />
          <text style={{ fg: COLORS.SHIMMER_HIGHLIGHT }}>
            {` ${props.step.title} ${props.elapsedTimeLabel}`}
          </text>
        </box>
        <For each={props.toolCalls}>
          {(display) => <ToolCallRow display={display} indent="     " />}
        </For>
      </Show>

      <Show when={props.step.status === "passed"}>
        <text>
          <span style={{ fg: COLORS.DIM }}>{`  ${num()}`}</span>
          <span style={{ fg: COLORS.GREEN }}>{` ${TICK} ${truncateLabel(label())}`}</span>
          <Show when={stepElapsedLabel()}>
            <span style={{ fg: COLORS.DIM }}>{` ${stepElapsedLabel()}`}</span>
          </Show>
        </text>
      </Show>

      <Show when={props.step.status === "failed"}>
        <text>
          <span style={{ fg: COLORS.DIM }}>{`  ${num()}`}</span>
          <span style={{ fg: COLORS.RED }}>{` ${CROSS} ${truncateLabel(label())}`}</span>
          <Show when={stepElapsedLabel()}>
            <span style={{ fg: COLORS.DIM }}>{` ${stepElapsedLabel()}`}</span>
          </Show>
        </text>
      </Show>

      <Show when={props.step.status === "skipped"}>
        <text>
          <span style={{ fg: COLORS.DIM }}>{`  ${num()}`}</span>
          <span style={{ fg: COLORS.YELLOW }}>{` ${ARROW_RIGHT} ${truncateLabel(label())}`}</span>
          <Show when={stepElapsedLabel()}>
            <span style={{ fg: COLORS.DIM }}>{` ${stepElapsedLabel()}`}</span>
          </Show>
        </text>
      </Show>

      <Show when={props.step.status === "pending"}>
        <text style={{ fg: COLORS.DIM }}>
          {`  ${num()} ${CIRCLE} ${props.step.title}`}
        </text>
      </Show>
    </box>
  );
};

interface ToolCallRowProps {
  readonly display: ToolCallDisplay;
  readonly indent: string;
}

const ToolCallRow = (props: ToolCallRowProps) => {
  const commandPreview = () => formatCommandPreview(props.display.rawInput);
  const argsPreview = () => {
    const cmd = commandPreview();
    return cmd ? formatArgsPreview(props.display.rawInput, cmd) : props.display.tool.args;
  };
  const hasResult = () => props.display.resultText !== undefined;
  const statusGlyph = () => (props.display.resultIsError ? CROSS : TICK);
  const statusColor = () => (props.display.resultIsError ? COLORS.RED : COLORS.GREEN);

  return (
    <box flexDirection="column">
      <text>
        <span style={{ fg: COLORS.DIM }}>{`${props.indent}${PIPE} `}</span>
        <Show when={props.display.isRunning}>
          <Spinner />
        </Show>
        <Show when={hasResult()}>
          <span style={{ fg: statusColor() }}>{statusGlyph()}</span>
        </Show>
        <Show when={!props.display.isRunning && !hasResult()}>
          <span style={{ fg: COLORS.DIM }}>{CIRCLE}</span>
        </Show>
        <span>{" "}</span>
        <span style={{ fg: COLORS.TEXT }}>{props.display.tool.name}</span>
        <Show when={commandPreview()}>
          <span>{`  `}</span>
          <span style={{ fg: COLORS.PRIMARY }}>{commandPreview()}</span>
        </Show>
        <Show when={argsPreview()}>
          <span>{`  `}</span>
          <span style={{ fg: COLORS.TEXT }}>{argsPreview()}</span>
        </Show>
        <Show when={!hasResult() && props.display.progressBytes !== undefined}>
          <span style={{ fg: COLORS.DIM }}>
            {`  ${POINTER} ${formatStreamingBytes(props.display.progressBytes!)} streaming`}
          </span>
        </Show>
        <Show when={hasResult() && props.display.resultTokens !== undefined}>
          <span style={{ fg: COLORS.DIM }}>
            {` ${ARROW_DOWN} ${formatTokenCount(props.display.resultTokens!)} tokens`}
          </span>
        </Show>
      </text>

      <Show when={hasResult() && props.display.resultText}>
        {(_resultText) => {
          const preview = () => formatResultPreview(props.display.resultText!);
          return (
            <Show when={preview()}>
              <text style={{ fg: COLORS.DIM }}>
                {`${props.indent}${PIPE}   ${ARROW_RIGHT} ${preview()}`}
              </text>
            </Show>
          );
        }}
      </Show>
    </box>
  );
};
